query GetOrdersQuery {
	orders {
		id
		charge
		total
		user {
			id
		}
		items {
			id
			name
			description
			price
			quantity
			photo {
				image {
					publicUrlTransformed
				}
			}
		}
	}
}
