name: GH Actions
on: [push, pull_request]
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: yarn
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn --immutable --immutable-cache --check-cache
      - name: Run tests
        working-directory: ./frontend
        run: yarn test
