name: GH Actions
on: [push, pull_request]
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.x'
          cache: 'yarn'
          cache-dependency-path: ./frontend/yarn.lock
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn --immutable --immutable-cache --check-cache
      - name: Run tests
        working-directory: ./frontend
        run: yarn test
