name: Github Actions
on: [push]
jobs:
  node:
    runs-on: ubuntu-latest
    env:
      COOKIE_SECRET: ARandomSecretWithMoreThan32Characters
      CLOUDINARY_CLOUD_NAME: grifemusic
      CLOUDINARY_KEY: 597576948711519
      CLOUDINARY_SECRET: ${{secrets.CLOUDINARY_SECRET}}
    steps:
      - name: Frontend Actions
        run: cd Frontend
      - name: Checkout on repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run Tests
      - run: yarn test
      # - name: Build Packages
      #   run: yarn next:build
